@startuml

node "Cliente Web"{
    artifact "Navegador" as navegador
}

node "Microservicio: Eventos, Actividades, Reservas y Reseñas" {
    package "infrastructure/adapters" {
        package "in/controllers"{
        }
        package "out/persistence"{
        }
        component Modulo2Adapter
    }
    package application{
    }
    package domain{
        package model{
        }
        package ports{
            package repository{
            }
            package "use cases"{
            }
        }
    }

    "in/controllers" --> "use cases"
    "out/persistence" ..> repository
    application ..> "use cases"
}

node "Microservicio: Sitios, Servicios,\n Reservas y Reseñas" {
}

Modulo2Adapter <- "Microservicio: Sitios, Servicios,\n Reservas y Reseñas"

node "Database Eventos, Actividades y Reservas"{
    database "eventos_actividades_reservas" as DB_SQL
}
node "Database Reseñas" {
    database "reseñas" as DB_Mongo
}
node "Database Preferencias Turista" {
    database "preferencias_eventos_actividades" as DB_Neo
}
"out/persistence" ---> DB_SQL
"out/persistence" ----> DB_Mongo
"out/persistence" ---> DB_Neo

navegador --> "in/controllers"

@enduml