@startuml

node "Cliente Web"{
    artifact "Navegador" as navegador
}

node "Microservicio: Reportes de Seguridad" {
    package "infrastructure/adapters" {
        package "in/controllers"{
        }
        package "out/persistence"{
        }
    }
    package application{
    }
    package domain{
        package model{
        }
        package ports{
            package repository{
            }
            package "use cases"{
            }
        }
    }

    "in/controllers" --> "use cases"
    "out/persistence" ..> repository
    application ..> "use cases"
}

node "Database Reportes Seguridad" {
    database "reportes_seguridad" as DB
}
"out/persistence" ---> DB

navegador --> "in/controllers"

@enduml